# Modified by DGG3D 2026: generates hdEmbreeBuildInfo.h containing the git
# commit hdEmbree was built from. Invoked with `cmake -P` from a custom
# target that runs on every build (see CMakeLists.txt), not just configure.
#
# Expected -D variables:
#   HDEMBREE_SOURCE_DIR    Repository root used for `git rev-parse`/`status`
#                          (whole repo, not just the plugin dir -- simpler
#                          than scoping the dirty check to hdEmbree alone,
#                          and still meaningful: any uncommitted change
#                          anywhere marks the build as "dirty").
#   HDEMBREE_OUTPUT_HEADER Path of the header to (re)write.

find_package(Git QUIET)

set(_commit "unknown")

if (GIT_EXECUTABLE)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
        WORKING_DIRECTORY "${HDEMBREE_SOURCE_DIR}"
        RESULT_VARIABLE _hdEmbree_revResult
        OUTPUT_VARIABLE _hdEmbree_revOutput
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    if (_hdEmbree_revResult EQUAL 0 AND NOT _hdEmbree_revOutput STREQUAL "")
        set(_commit "${_hdEmbree_revOutput}")

        execute_process(
            COMMAND "${GIT_EXECUTABLE}" status --porcelain
            WORKING_DIRECTORY "${HDEMBREE_SOURCE_DIR}"
            RESULT_VARIABLE _hdEmbree_statusResult
            OUTPUT_VARIABLE _hdEmbree_statusOutput
            ERROR_QUIET
        )
        if (_hdEmbree_statusResult EQUAL 0 AND NOT _hdEmbree_statusOutput STREQUAL "")
            set(_commit "${_commit}-dirty")
        endif()
    endif()
endif()

set(_content
"// Generated by hdEmbreeBuildInfo.cmake -- do not edit.
#pragma once
#define HDEMBREE_BUILD_COMMIT \"${_commit}\"
")

# Only touch the file when the content actually changes, so an unmodified
# commit doesn't force hdEmbree.cpp translation units to recompile every
# build.
set(_writeFile TRUE)
if (EXISTS "${HDEMBREE_OUTPUT_HEADER}")
    file(READ "${HDEMBREE_OUTPUT_HEADER}" _existingContent)
    if (_existingContent STREQUAL _content)
        set(_writeFile FALSE)
    endif()
endif()

if (_writeFile)
    file(WRITE "${HDEMBREE_OUTPUT_HEADER}" "${_content}")
endif()
